source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# add 
gem 'devise', '>= 4.6.0'
gem 'cancancan'
gem 'jquery-rails'
gem 'jquery_mask_rails', '~> 0.1.0'
gem 'cocoon'
gem 'simplecov', require: false, group: :test
gem 'geocoder'
gem 'plotly-rails-js'
gem 'carrierwave', '~> 1.0'
gem 'money-rails', '~>1.12'
gem 'ransack'
gem 'rails', '~> 5.2.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'simplecov', require: false, group: :test

# Mikrotik
gem 'mtik'
# Logs
gem 'audited'
gem 'notable' # performace

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'annotate'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "better_errors"
  gem "binding_of_caller"
end

group :test do
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Alerts github
gem 'actionview', '>= 5.2.2.1'
gem 'railties', '>= 5.2.2.1'
gem 'rack', '>= 2.0.6'
gem 'loofah', '>= 2.2.3'
gem "nokogiri", ">= 1.10.4"


